# Server Configuration
server:
  port: 8080

# Application Configuration
spring:
  application:
    name: ai-service
  
  # Ollama Configuration
  ai:
    ollama:
      base-url: http://localhost:11434
      temperature: 0.7
      init:
        pull-model-strategy: never
      chat:
        model: deepseek-r1:1.5b
      embedding:
        options:
          model: nomic-embed-text
      client:
        connection-timeout: 30000
        read-timeout: 30000
    model:
      embedding: ollama
    vectorstore:
      redis:
        initialize-schema: true
        index-name: bank_knowledge
        prefix: embedding
        dimensions: 768
        enabled: true
  
  # Redis Configuration
  data:
    redis:
      host: 192.168.162.40
      port: 6379
      password: 123456
      client-type: jedis
      database: 0

# Logging Configuration
logging:
  level:
    root: INFO
    org.springframework: DEBUG
    org.springframework.data.redis: DEBUG
    org.springframework.boot.autoconfigure: DEBUG
    com.bank.aiservice: DEBUG
    org.springframework.beans.factory.support: DEBUG

  file:
    name: logs/ai-service.log
    max-size: 10MB
    max-history: 30
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# CORS Configuration (Commented out)
# spring:
#   webflux:
#     cors:
#       allowed-origins: "*"
#       allowed-methods: GET,POST,PUT,DELETE,OPTIONS
#       allowed-headers: "*"
#       max-age: 3600 

debug: true 